# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Enigma.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        Form.setMinimumSize(QtCore.QSize(400, 500))
        Form.setMaximumSize(QtCore.QSize(400, 500))
        Form.setWindowOpacity(1.0)
        Form.setStyleSheet("background-color: rgb(23, 33, 43);")
        self.pushButtonEncryptionS = QtWidgets.QPushButton(Form)
        self.pushButtonEncryptionS.setGeometry(QtCore.QRect(30, 110, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonEncryptionS.setFont(font)
        self.pushButtonEncryptionS.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonEncryptionS.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonEncryptionS.setAutoDefault(True)
        self.pushButtonEncryptionS.setDefault(False)
        self.pushButtonEncryptionS.setFlat(False)
        self.pushButtonEncryptionS.setObjectName("pushButtonEncryptionS")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(48, 163, 230);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButtonDecryptionS = QtWidgets.QPushButton(Form)
        self.pushButtonDecryptionS.setGeometry(QtCore.QRect(200, 110, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonDecryptionS.setFont(font)
        self.pushButtonDecryptionS.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonDecryptionS.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonDecryptionS.setAutoDefault(True)
        self.pushButtonDecryptionS.setDefault(False)
        self.pushButtonDecryptionS.setFlat(False)
        self.pushButtonDecryptionS.setObjectName("pushButtonDecryptionS")
        self.pushButtonEncryption2E = QtWidgets.QPushButton(Form)
        self.pushButtonEncryption2E.setGeometry(QtCore.QRect(30, 200, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonEncryption2E.setFont(font)
        self.pushButtonEncryption2E.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonEncryption2E.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonEncryption2E.setAutoDefault(True)
        self.pushButtonEncryption2E.setDefault(False)
        self.pushButtonEncryption2E.setFlat(False)
        self.pushButtonEncryption2E.setObjectName("pushButtonEncryption2E")
        self.pushButtonDecryption2D = QtWidgets.QPushButton(Form)
        self.pushButtonDecryption2D.setGeometry(QtCore.QRect(200, 200, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonDecryption2D.setFont(font)
        self.pushButtonDecryption2D.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonDecryption2D.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonDecryption2D.setAutoDefault(True)
        self.pushButtonDecryption2D.setDefault(False)
        self.pushButtonDecryption2D.setFlat(False)
        self.pushButtonDecryption2D.setObjectName("pushButtonDecryption2D")
        self.pushButtonEncryptionER = QtWidgets.QPushButton(Form)
        self.pushButtonEncryptionER.setGeometry(QtCore.QRect(30, 290, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonEncryptionER.setFont(font)
        self.pushButtonEncryptionER.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonEncryptionER.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonEncryptionER.setAutoDefault(True)
        self.pushButtonEncryptionER.setDefault(False)
        self.pushButtonEncryptionER.setFlat(False)
        self.pushButtonEncryptionER.setObjectName("pushButtonEncryptionER")
        self.pushButtonDecryptionRD = QtWidgets.QPushButton(Form)
        self.pushButtonDecryptionRD.setGeometry(QtCore.QRect(200, 290, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonDecryptionRD.setFont(font)
        self.pushButtonDecryptionRD.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonDecryptionRD.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonDecryptionRD.setAutoDefault(True)
        self.pushButtonDecryptionRD.setDefault(False)
        self.pushButtonDecryptionRD.setFlat(False)
        self.pushButtonDecryptionRD.setObjectName("pushButtonDecryptionRD")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 73, 141, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 141, 20))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 141, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.labelStatus = QtWidgets.QLabel(Form)
        self.labelStatus.setGeometry(QtCore.QRect(0, 460, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(48, 163, 230);")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 350, 141, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButtonEncryptionDER = QtWidgets.QPushButton(Form)
        self.pushButtonEncryptionDER.setGeometry(QtCore.QRect(30, 380, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonEncryptionDER.setFont(font)
        self.pushButtonEncryptionDER.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonEncryptionDER.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonEncryptionDER.setAutoDefault(True)
        self.pushButtonEncryptionDER.setDefault(False)
        self.pushButtonEncryptionDER.setFlat(False)
        self.pushButtonEncryptionDER.setObjectName("pushButtonEncryptionDER")
        self.pushButtonDecryptionDRD = QtWidgets.QPushButton(Form)
        self.pushButtonDecryptionDRD.setGeometry(QtCore.QRect(200, 380, 171, 53))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButtonDecryptionDRD.setFont(font)
        self.pushButtonDecryptionDRD.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonDecryptionDRD.setStyleSheet("background-color: rgb(36, 47, 61);\n"
"color: rgb(84, 157, 219);")
        self.pushButtonDecryptionDRD.setAutoDefault(True)
        self.pushButtonDecryptionDRD.setDefault(False)
        self.pushButtonDecryptionDRD.setFlat(False)
        self.pushButtonDecryptionDRD.setObjectName("pushButtonDecryptionDRD")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Enigma"))
        self.pushButtonEncryptionS.setText(_translate("Form", "Simple Encryption"))
        self.label_4.setText(_translate("Form", "Enigma Encrypter/Decrypter"))
        self.pushButtonDecryptionS.setText(_translate("Form", "Simple Decryption"))
        self.pushButtonEncryption2E.setText(_translate("Form", "Double Encryption"))
        self.pushButtonDecryption2D.setText(_translate("Form", "Double Decryption"))
        self.pushButtonEncryptionER.setText(_translate("Form", "Revese Encryption"))
        self.pushButtonDecryptionRD.setText(_translate("Form", "Reverse Decryption"))
        self.label.setText(_translate("Form", "Low security level :"))
        self.label_2.setText(_translate("Form", "Medium security level :"))
        self.label_3.setText(_translate("Form", "High security Level :"))
        self.labelStatus.setText(_translate("Form", "Status: Standby"))
        self.label_5.setText(_translate("Form", "Extreme security Level :"))
        self.pushButtonEncryptionDER.setText(_translate("Form", "Revese Double Encryption"))
        self.pushButtonDecryptionDRD.setText(_translate("Form", "Reverse Double Decryption"))
